### ISSUE TITLE
I'm running into errors when I try to compile - log file pasted into the comment - thoughts?

### ISSUE THREAD

**Issue by ThomasPosen** [iandol/scrivomatic#39]
=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.29 Report @ 2020-10-26 16:55:28 -0400 ===
=== ------------------------------------------------------ ===
 Working directory: /Users/tposen/Desktop/workflow-mmd
 Initiating with Ruby 2.6.3
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="Workflow.md", output=nil, to=nil, yaml="pandocomatic.yaml", command="pandocomatic", envpath="/Users/tposen/bin:/usr/local/bin", build=false, cleanup=false, verbose=true, dry_run=false, open_log=true, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/tposen/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.9.2.1
---pandocomatic: /usr/local/bin/pandocomatic | V: 0.2.7.3
---ruby: /usr/bin/ruby | V: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
---rbenv versions:
---gem: /usr/bin/gem
---python: /usr/bin/python

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /usr/local/bin/pandocomatic -c pandocomatic.yaml --debug Workflow.md 
::: (5) + converting /Users/tposen/Desktop/workflow-mmd/Workflow.md 4 times:
::: (4)   - convert Workflow.md -> Workflow.tex
::: pandoc	--from=markdown \
::: 	--to=latex \
::: 	--template=custom.latex \
::: 	--toc \
::: 	--toc-depth=4 \
::: 	--filter=assimilateMetadata.rb \
::: 	--standalone \
::: 	--bibliography=workflow.bib \
::: 	--csl=apa-workflow.csl
::: /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/attr.rb:48:in `[]': odd number of arguments for Hash (ArgumentError)
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/attr.rb:48:in `initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/table.rb:56:in `new'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/table.rb:56:in `initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/node.rb:119:in `new'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/node.rb:119:in `block in initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/node.rb:117:in `each'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/node.rb:117:in `initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/document.rb:118:in `initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/document.rb:85:in `new'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/document.rb:85:in `from_JSON'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter.rb:336:in `read_document'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter.rb:277:in `filter'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter.rb:251:in `run'
::: 	from ./assimilateMetadata.rb:74:in `<main>'
::: Error running filter assimilateMetadata.rb:
::: Filter returned error status 1
::: Error running pandoc => error while running:
::: 
::: pandoc	--from=markdown \
::: 	--to=latex \
::: 	--template=custom.latex \
::: 	--toc \
::: 	--toc-depth=4 \
::: 	--filter=assimilateMetadata.rb \
::: 	--standalone \
::: 	--bibliography=workflow.bib \
::: 	--csl=apa-workflow.csl
::: 
::: Pandoc responded with:
::: 
::: /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/attr.rb:48:in `[]': odd number of arguments for Hash (ArgumentError)
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/attr.rb:48:in `initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/table.rb:56:in `new'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/table.rb:56:in `initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/node.rb:119:in `new'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/node.rb:119:in `block in initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/node.rb:117:in `each'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/node.rb:117:in `initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/document.rb:118:in `initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/document.rb:85:in `new'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter/document.rb:85:in `from_JSON'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter.rb:336:in `read_document'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter.rb:277:in `filter'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2/lib/paru/filter.rb:251:in `run'
::: 	from ./assimilateMetadata.rb:74:in `<main>'
::: Error running filter assimilateMetadata.rb:
::: Filter returned error status 1
::: 
:: exit status: pid 10953 exit 243

!!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic -c pandocomatic.yaml --debug Workflow.md !!!

**Comment by iandol** [comment]
Hi @ThomasPosen — try upgrading to the latest Pandoc, as far as I can see you are using an old Pandoc with the latest pandocomatic and paru, read here to see that rhse new versions are not backwards compatible with an older pandoc https://github.com/htdebeer/pandocomatic/releases/tag/0.2.7.3

The other alternative is to install the older versions of paru and pandocomatic, you can use the `-v` flag with gem to install a specific gem version...
