### ISSUE TITLE
Filter errors after update

### ISSUE THREAD

**Issue by bokamm** [iandol/scrivomatic#45]
Hallo!
A couple of days ago, I updated my system to macOS 12.0.1 (from Big Sur). I did not encounter any issues when compiling from Scrivener via scrivomatic. However, today I updated brew, pandocomatic etc. and since then, run into errors with the filters.
I downloaded the "working pandoc folder" again, updated the script in my Scrivener formats, tried to switch ruby versions with rbenv, and when that did not help, uninstalled brew and everything, re-installed following the instructions, but to no avail.
When I switch off the filters in the yaml-file, I receive another error, this time with pandocomatic itself.

Is there anything you can spot in the logs that would indicate what I can do to fix the issue?
Using the Workflow example results in the same errors.

Thank you for any hints!

**1. With filters enabled:**
```
=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.30 Report @ 2021-11-11 15:51:26 +0900 ===
=== ------------------------------------------------------ ===
 Running shell: /bin/zsh
 Working directory: /Users/username/Desktop/OutputFile.md
 Initiating with Ruby 2.6.8
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="OutputFile.md", output=nil, to=nil, yaml=nil, command="pandocomatic", envpath="/Users/username/bin:/Library/TeX/texbin:/usr/local/bin", build=true, cleanup=false, verbose=true, dry_run=false, open_log=false, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/username/bin:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Scrivener.app/Contents/Resources/MultiMarkdown/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.16.1
---pandocomatic: /usr/local/bin/pandocomatic | V: 0.2.7.7
---ruby: /usr/bin/ruby | V: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
---rbenv versions:
---gem: /usr/bin/gem
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /usr/local/bin/pandocomatic --debug OutputFile.md 
::: pandoc	--from=markdown \
::: 	--to=html5 \
::: 	--standalone \
::: 	--section-divs \
::: 	--mathjax \
::: 	--lua-filter=/Users/username/.local/share/pandoc/filters/pagebreak.lua \
::: 	--filter=/Users/username/.local/share/pandoc/filters/assimilateMetadata.rb \
::: 	--template=/Users/username/.local/share/pandoc/templates/mytemplate.html \
::: 	--css=/Users/username/.local/share/pandoc/templates/mytemplate.css \
::: 	--toc \
::: 	--toc-depth=3 \
::: 	--verbose \
::: 	--citeproc \
::: 	--bibliography=/Users/username/.local/share/pandoc/bibs/mytemplate_2_Cthulhu.json \
::: 	--csl=/Users/username/.local/share/pandoc/csl/jrpg.csl \
::: 	--citation-abbreviations=/Users/username/.local/share/pandoc/cite-abbr.json \
::: 	--reference-links
::: [INFO] Loaded /Users/username/.local/share/pandoc/templates/mytemplate.html from /Users/username/.local/share/pandoc/templates/mytemplate.html
::: [INFO] Running filter /Users/username/.local/share/pandoc/filters/pagebreak.lua
::: [INFO] Completed filter /Users/username/.local/share/pandoc/filters/pagebreak.lua in 19 ms
::: [INFO] Running filter /Users/username/.local/share/pandoc/filters/assimilateMetadata.rb
::: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:271:in `load': unknown keyword: permitted_classes (ArgumentError)
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2.4/lib/paru/filter/metadata.rb:52:in `initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2.4/lib/paru/filter.rb:279:in `new'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2.4/lib/paru/filter.rb:279:in `filter'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2.4/lib/paru/filter.rb:251:in `run'
::: 	from /Users/username/.local/share/pandoc/filters/assimilateMetadata.rb:77:in `<main>'
::: Error running filter /Users/username/.local/share/pandoc/filters/assimilateMetadata.rb:
::: Filter returned error status 1
::: Error running pandoc => error while running:
::: 
::: pandoc	--from=markdown \
::: 	--to=html5 \
::: 	--standalone \
::: 	--section-divs \
::: 	--mathjax \
::: 	--lua-filter=/Users/username/.local/share/pandoc/filters/pagebreak.lua \
::: 	--filter=/Users/username/.local/share/pandoc/filters/assimilateMetadata.rb \
::: 	--template=/Users/username/.local/share/pandoc/templates/mytemplate.html \
::: 	--css=/Users/username/.local/share/pandoc/templates/mytemplate.css \
::: 	--toc \
::: 	--toc-depth=3 \
::: 	--verbose \
::: 	--citeproc \
::: 	--bibliography=/Users/username/.local/share/pandoc/bibs/mybib.json \
::: 	--csl=/Users/username/.local/share/pandoc/csl/jrpg.csl \
::: 	--citation-abbreviations=/Users/username/.local/share/pandoc/cite-abbr.json \
::: 	--reference-links
::: 
::: Pandoc responded with:
::: 
::: [INFO] Loaded /Users/username/.local/share/pandoc/templates/mytemplate.html from /Users/username/.local/share/pandoc/templates/mytemplate.html
::: [INFO] Running filter /Users/username/.local/share/pandoc/filters/pagebreak.lua
::: [INFO] Completed filter /Users/username/.local/share/pandoc/filters/pagebreak.lua in 19 ms
::: [INFO] Running filter /Users/username/.local/share/pandoc/filters/assimilateMetadata.rb
::: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:271:in `load': unknown keyword: permitted_classes (ArgumentError)
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2.4/lib/paru/filter/metadata.rb:52:in `initialize'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2.4/lib/paru/filter.rb:279:in `new'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2.4/lib/paru/filter.rb:279:in `filter'
::: 	from /Library/Ruby/Gems/2.6.0/gems/paru-0.4.2.4/lib/paru/filter.rb:251:in `run'
::: 	from /Users/username/.local/share/pandoc/filters/assimilateMetadata.rb:77:in `<main>'
::: Error running filter /Users/username/.local/share/pandoc/filters/assimilateMetadata.rb:
::: Filter returned error status 1
::: 
:: exit status: pid 4936 exit 243

!!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic --debug OutputFile.md !!!

===------ RUN LATEXMK on OutputFile.tex: ------===
!!!---Scrivomatic postBuild: could not find OutputFile.tex
```

**2. Without filters:**

```
=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.30 Report @ 2021-11-11 15:53:22 +0900 ===
=== ------------------------------------------------------ ===
 Running shell: /bin/zsh
 Working directory: /Users/username/Desktop/OutputFile.md
 Initiating with Ruby 2.6.8
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="OutputFile.md", output=nil, to=nil, yaml=nil, command="pandocomatic", envpath="/Users/username/bin:/Library/TeX/texbin:/usr/local/bin", build=true, cleanup=false, verbose=true, dry_run=false, open_log=false, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/username/bin:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Scrivener.app/Contents/Resources/MultiMarkdown/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.16.1
---pandocomatic: /usr/local/bin/pandocomatic | V: 0.2.7.7
---ruby: /usr/bin/ruby | V: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
---rbenv versions:
---gem: /usr/bin/gem
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /usr/local/bin/pandocomatic --debug OutputFile.md 
::: An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
::: /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/configuration.rb:666:in `is_local_path?': undefined method `start_with?' for nil:NilClass (NoMethodError)
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/configuration.rb:554:in `update_path'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/convert_file_command.rb:192:in `block (2 levels) in pandoc'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/convert_file_command.rb:186:in `each'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/convert_file_command.rb:186:in `block in pandoc'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/convert_file_command.rb:184:in `chdir'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/convert_file_command.rb:184:in `pandoc'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/convert_file_command.rb:135:in `convert_file'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/convert_file_command.rb:86:in `run'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/command.rb:129:in `execute'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/convert_file_multiple_command.rb:99:in `block in execute'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/convert_file_multiple_command.rb:98:in `each'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/command/convert_file_multiple_command.rb:98:in `execute'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/pandocomatic.rb:105:in `run'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/bin/pandocomatic:3:in `<top (required)>'
::: 	from /usr/local/bin/pandocomatic:23:in `load'
::: 	from /usr/local/bin/pandocomatic:23:in `<main>'
:: exit status: pid 5027 exit 1

!!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic --debug OutputFile.md !!!

===------ RUN LATEXMK on OutputFile.tex: ------===
!!!---Scrivomatic postBuild: could not find OutputFile.tex

```

**Comment by iandol** [comment]
Hi @bokamm — this seems to be an error in the psych gem. @htdebeer and I recently saw an error with the new version of psych (https://github.com/htdebeer/paru/issues/63), and the new version of paru (0.4.2.4) and pandocomatic (0.2.7.7) fixed it. But I wonder if fixing that caused a regression error with the old versions of psych? 

I am using Ruby V3.0.2 (via rbenv) and the latest versions of all gems (Psych is at 4.0.2), and I don't see any error. BUT if I use rbenv to revert to the system Ruby (V2.6.8, psych V3.1.0) then I also see the same error that you do:

```
::: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:271:in `load': unknown keyword: permitted_classes (ArgumentError)
```

The error suggests that Psych V3.1.0 does not support the method used to fix the problem. I think @htdebeer can probably think of a better solution.

In the mean time, you can either force update the psych library that is part of the system Ruby:

```
sudo gem update psych
```

Or update to Ruby V3.0.2 using rbenv and update all gems to the latest version (`gem update`).

**Comment by iandol** [comment]
You second error is more of a mystery:

```
/Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.7/lib/pandocomatic/configuration.rb:666:in `is_local_path?': undefined method `start_with?' for nil:NilClass (NoMethodError)
```

...but suggests some issue with the pandocomatic.yaml or metadata in removing the filters.

**Comment by bokamm** [comment]
Hallo @iandol , thank you so much for the quick response!
Force updating psych did the trick! Compile works again. What a relief!

As for the second error, the pandocomatic.yaml is the one downloaded with the "working folder," where I changed only file-paths to templates, csl files etc.
However, I will have a look at the metadata frontmatter if anything is amiss there.

**Comment by iandol** [comment]
You can attach them here and I can have a peek. Paru and pandocomatic have now been fixed to work around the psych library issue, thanks to @htdebeer!

**Comment by bokamm** [comment]
Paru and pandocomatic fix: great!

As for the metadata, they look like this:

```
# Standard Scrivener + Pandoc[omatic] Project YAML metadata
# IMPORTANT: YAML configuration files use SPACES for indentation to 
# define structure, remember to straighten any smart quotes, and don't
# capitalise metadata keys like "author" or "title", they must be 
# lowercase! Use "Show Invisibles" in Scrivener to see spaces.
section: Case Report | 実践報告
title: xy
subtitle: xy
author:
  - name: Lastname Firstname | 氏名 名前
    affiliation: 1
#    equal_contributor: true
#    correspondence: xx
institute:
  - 1 Independent Scholar | 独立研究者
keywords:
  - xy
  - xy
#citation_en: Lastname, Firstname. 2021. "xy." Journal, 2: x-xx.
#citation_jp: 氏名 名前. 2021.「xy」『研究』2号: 
doi: 10.xxx/xxx_2_xx
#compiled: <$shortdate>
#date: <$fulldate>
#comments: ""
# Select which templates pandocomatic will use
# you can enter overrides to the templates here as well
pandocomatic_:
  use-template:
#    - docx-refs
    - html-refs
#    - pdf-refs
```

I never managed to get the citation entries working, they always broke the compilation. Best to remove them completely, I think.

**Comment by iandol** [comment]
I can reproduce your second error. The problem is if you comment out a filter but leave the filter specifier in:

```yaml
  html:
    pandoc:
      from: markdown
      to: html5
      standalone: true
      number-sections: false
      section-divs: true
      mathjax: true
      filter: 
        #- filters/assimilateMetadata.rb #regularise metadata
      template: 'templates/custom.html'
```

You are passing an empty filter declaration which triggers this error in Ruby:

```
:: Running: /Users/ian/.rbenv/shims/pandocomatic --debug mdata.md
::: An unexpected error has occurred. You can report this bug via https://github.com/htdebeer/pandocomatic/issues/new.
::: /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.7.8/lib/pandocomatic/configuration.rb:666:in `is_local_path?': undefined method `start_with?' for nil:NilClass (NoMethodError)
```

If you also comment out `filter:` then there is no error.

**Comment by bokamm** [comment]
Thank you so, so much for clarifying this!

**Comment by iandol** [comment]
@bokamm — just to mention that paru and pandocomatic (run `gem update paru pandocomatic`) have been upgraded so they handle empty lists in the YAML, so commenting out filters will not cause an error anymore
